Repository 100-hours-a-week/7-team-ddb-ai, pull requests merged in 2025-05, with the labels that each got.

#17 Feat/#11
  fastapi_app/app/api/v1/endpoints/recommend.py
  fastapi_app/app/schemas/recommend_schema.py
  fastapi_app/app/services/recommender.py
  fastapi_app/app/services/vector_store.py
  fastapi_app/requirements.txt
Labels: AI

#20 Feat/#19
  fastapi_app/app/api/deps.py
  fastapi_app/app/api/v1/endpoints/recommend.py
  fastapi_app/app/cache/redis.py
  fastapi_app/app/core/config.py
  fastapi_app/app/database/session.py
  fastapi_app/app/logging/config.py
  fastapi_app/app/services/recommender.py
  fastapi_app/requirements.txt
Labels: AI

#23 Feat/#15
  fastapi_app/app/api/deps.py
  fastapi_app/app/core/config.py
  fastapi_app/app/services/vector_store.py
  fastapi_app/requirements.txt
  requirements.txt
Labels: AI

#25 Feat/#15
  fastapi_app/app/api/deps.py
  fastapi_app/app/core/config.py
  fastapi_app/app/services/vector_store.py
  fastapi_app/requirements.txt
  requirements.txt
Labels: AI

#28 Fix/#27
  fastapi_app/app/services/vector_store.py
  fastapi_app/requirements.txt
Labels: Bug-hard, AI

#36 Feat/#14
  fastapi_app/app/api/deps.py
  fastapi_app/app/core/constants.py
  fastapi_app/app/services/recommend_engine.py
  fastapi_app/app/services/recommender.py
  fastapi_app/app/services/vector_store.py
  fastapi_app/main.py
Labels: AI

#37 Feat/#29
  fastapi_app/app/data/make_chroma_db.py
  fastapi_app/app/data/more_data_for_postgres.csv
  fastapi_app/app/data/more_place_outputs.jsonl
Labels: AI

#40 Chore/#38
  fastapi_app/requirements.txt
Labels: AI

#43 Feat/#42
  fastapi_app/app/data/chroma_db.py
  fastapi_app/app/data/data_for_postgres.csv
  fastapi_app/app/data/make_chroma_db.py
  fastapi_app/app/data/place_outputs.jsonl
  fastapi_app/app/services/vector_store.py
Labels: AI

#48 refactor : 프롬프트 개선
  fastapi_app/app/services/recommender.py
Labels: AI

#49 Fix/#44
  fastapi_app/app/data/chroma_db.py
  fastapi_app/app/data/data_for_postgres.csv
  fastapi_app/app/data/place_id_category_data.csv
  fastapi_app/app/data/place_keywords.jsonl
  fastapi_app/app/services/vector_store.py
Labels: AI

#50 Feat/#45
  fastapi_app/app/core/constants.py
  fastapi_app/app/data/chroma_db.py
Labels: AI

#53 Refactor/#46
  fastapi_app/app/services/recommend_engine.py
  fastapi_app/app/services/vector_store.py
Labels: AI

#69 chore : 카테고리 개선으로 인한 프롬프트 수정
  fastapi_app/app/services/recommender.py
Labels: AI

#71 Chore/#55
  fastapi_app/app/api/deps.py
  fastapi_app/app/services/recommend_engine.py
  fastapi_app/app/services/recommender.py
  fastapi_app/app/services/vector_store.py
  fastapi_app/main.py
Labels: AI

#74 Docs/#72
  fastapi_app/docs/deployment/01_git-bastion-manual.md
  fastapi_app/docs/deployment/02_jenkins-terraform.md
  fastapi_app/docs/deployment/03_docker-deployment.md
  fastapi_app/docs/deployment/04_kubeadm-orchestration.md
  fastapi_app/docs/deployment/05_k8s-automation.md
  fastapi_app/docs/deployment/README.md
Labels: AI

#75 Chore/#63
  fastapi_app/requirements.txt
Labels: AI

#76 Dev
  fastapi_app/app/api/deps.py
  fastapi_app/app/services/recommend_engine.py
  fastapi_app/app/services/recommender.py
  fastapi_app/app/services/vector_store.py
  fastapi_app/docs/deployment/01_git-bastion-manual.md
  fastapi_app/docs/deployment/02_jenkins-terraform.md
  fastapi_app/docs/deployment/03_docker-deployment.md
  fastapi_app/docs/deployment/04_kubeadm-orchestration.md
  fastapi_app/docs/deployment/05_k8s-automation.md
  fastapi_app/docs/deployment/README.md
  fastapi_app/main.py
  fastapi_app/requirements.txt
Labels: AI

#79 Chore/#78
  fastapi_app/main.py
Labels: AI

#83 Fix/#82
  fastapi_app/app/services/recommend_engine.py
Labels: AI

#85 chore : 장소 카테고리 프롬프트 반영
  fastapi_app/app/services/recommender.py
Labels: AI

#89 Fix/#88
  fastapi_app/app/services/recommend_engine.py
Labels: AI

#98 Feat/#59
  fastapi_app/app/api/deps.py
  fastapi_app/app/core/config.py
  fastapi_app/app/logging/config.py
  fastapi_app/app/logging/di.py
  fastapi_app/app/services/recommend_engine.py
  fastapi_app/app/services/recommender.py
  fastapi_app/app/services/vector_store.py
  fastapi_app/main.py
Labels: AI

#101 Release : 로깅 구현 및 추천 시각화를 위한 키워드 반환
  fastapi_app/app/api/deps.py
  fastapi_app/app/core/config.py
  fastapi_app/app/logging/config.py
  fastapi_app/app/logging/di.py
  fastapi_app/app/schemas/recommend_schema.py
  fastapi_app/app/services/recommend_engine.py
  fastapi_app/app/services/recommender.py
  fastapi_app/app/services/vector_store.py
  fastapi_app/main.py
Labels: AI

#104 chore : 프로젝트 구조 정리
  fastapi_app/app/cache/decorators.py
  fastapi_app/app/core/init_app.py
  fastapi_app/app/database/migrations/__init__.py
  fastapi_app/app/database/session.py
  fastapi_app/app/exceptions/custom.py
  fastapi_app/app/exceptions/handlers.py
  fastapi_app/app/logging/middleware.py
  fastapi_app/app/ml/inference.py
  fastapi_app/app/ml/model_loader.py
  fastapi_app/app/models/base.py
  fastapi_app/app/models/place.py
  fastapi_app/app/services/prompt_manager.py
  fastapi_app/app/services/rag_engine.py
  fastapi_app/app/tasks/celery.py
  fastapi_app/app/tasks/workers/__init__.py
  fastapi_app/app/utils/logger.py
  fastapi_app/app/utils/text_cleaner.py
  fastapi_app/app/utils/timer.py
  fastapi_app/docker-compose.yml
  fastapi_app/docs/api/README.md
  fastapi_app/docs/architecture/README.md
Labels: AI

#105 chore : PR / issue template 수정
  .github/ISSUE_TEMPLATE/issue.md
  .github/pull_request_template.md
Labels: AI

#106 Chore : 프로젝트 구조 수정
  .github/ISSUE_TEMPLATE/issue.md
  .github/pull_request_template.md
  fastapi_app/app/cache/decorators.py
  fastapi_app/app/core/init_app.py
  fastapi_app/app/database/migrations/__init__.py
  fastapi_app/app/database/session.py
  fastapi_app/app/exceptions/custom.py
  fastapi_app/app/exceptions/handlers.py
  fastapi_app/app/logging/middleware.py
  fastapi_app/app/ml/inference.py
  fastapi_app/app/ml/model_loader.py
  fastapi_app/app/models/base.py
  fastapi_app/app/models/place.py
  fastapi_app/app/services/prompt_manager.py
  fastapi_app/app/services/rag_engine.py
  fastapi_app/app/tasks/celery.py
  fastapi_app/app/tasks/workers/__init__.py
  fastapi_app/app/utils/logger.py
  fastapi_app/app/utils/text_cleaner.py
  fastapi_app/app/utils/timer.py
  fastapi_app/docker-compose.yml
  fastapi_app/docs/api/README.md
  fastapi_app/docs/architecture/README.md
Labels: AI

#102 deploy : Jenkinsfile 작성
  fastapi_app/Jenkinsfile
Labels: AI

#108 Release : 모니터링 구축, CICD
  fastapi_app/Jenkinsfile
  fastapi_app/app/api/deps.py
  fastapi_app/app/api/v1/endpoints/recommend.py
  fastapi_app/app/services/recommender.py
  fastapi_app/main.py
  fastapi_app/monitoring/grafana/README.md
  fastapi_app/monitoring/metrics.py
  fastapi_app/monitoring/prometheus/README.md
  fastapi_app/requirements.txt
Labels: AI

#109 deploy: Jenkis Discord Webhook 추가
  fastapi_app/Jenkinsfile
Labels: AI

#120 Fix/#116
  fastapi_app/app/logging/config.py
  fastapi_app/main.py
Labels: Bug-soft, AI

#125 chore : 콘솔 info log 삭제
  fastapi_app/Dockerfile
Labels: AI

#135 feat : 메모리 정리 명령어 추가
  fastapi_app/Jenkinsfile
Labels: AI
